version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_expense_tracker
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/db_expense_tracker
    volumes:
      - ./backend:/app
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run build:frontend &&
             node index.js"

volumes:
  mysql_data:
